version: '3.8'

services:
  shop:
    build: .
    environment:
      APP_ENV: dev
    user: 1000
    volumes:
      - ./:/var/www/shop
      - composer_data:/var/data/composer

  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop_password
    restart: "no"
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    command: -p 5432
    logging:
      driver: local

volumes:
  composer_data:
  pg_data: